RustboroCity_House4_MapScripts::
	.byte 0



RustboroCity_EventScript_BoyHouse::
	msgbox RustboroCity_Text_BoyHouse, MSGBOX_NPC
	end


RustboroCity_Text_BoyHouse:
	.string "I always see 'em, carrying stuff from\n"
	.string "the factory on their trucks.\p"
	.string "But what are they carrying?\n"
	.string "I 'unno.$"


RustboroCity_EventScript_GirlHouse::
	msgbox RustboroCity_Text_GirlHouse, MSGBOX_NPC
	end


RustboroCity_Text_GirlHouse:
	.string "Our toilet's clogged.\p"
	.string "…Hey, don't look at me like\n"
	.string "that!\p"
	.string "Something's wrong with the sewer\n"
	.string "system, is all.$"