GraniteCave_1F_MapScripts::
	.byte 0

GraniteCave_EventScript_Magma1::
	trainerbattle_single TRAINER_GRANITE_GRUNT_1, GraniteCave_Text_Magma1Intro, GraniteCave_Text_Magma1Defeated
	msgbox GraniteCave_Text_Magma1Post, MSGBOX_AUTOCLOSE
	end


GraniteCave_Text_Magma1Intro:
	.string "This mine has been seized by\n"
	.string "Team Magma!\p"
	.string "No intruders allowed!$"


GraniteCave_Text_Magma1Defeated:
	.string "Aw, dang it…$"

GraniteCave_Text_Magma1Post:
	.string "Fine, go ahead.\n"
	.string "I don't get paid enough for this.\p"
	.string "In fact, I don't get paid at all.$"


GraniteCave_EventScript_Magma2::
	trainerbattle_single TRAINER_GRANITE_GRUNT_2, GraniteCave_Text_Magma2Intro, GraniteCave_Text_Magma2Defeated
	msgbox GraniteCave_Text_Magma2Post, MSGBOX_AUTOCLOSE
	end


GraniteCave_Text_Magma2Intro:
	.string "We're gonna make so much money off\n"
	.string "this cave!$"


GraniteCave_Text_Magma2Defeated:
	.string "You're too strong…$"

GraniteCave_Text_Magma2Post:
	.string "We need the money to finance our\n"
	.string "organization.\p"
	.string "One day, you'll be thanking us.$"



GraniteCave_EventScript_Magma3::
	trainerbattle_single TRAINER_GRANITE_GRUNT_3, GraniteCave_Text_Magma3Intro, GraniteCave_Text_Magma3Defeated
	msgbox GraniteCave_Text_Magma3Post, MSGBOX_AUTOCLOSE
	end


GraniteCave_Text_Magma3Intro:
	.string "Hands off the generator!$"


GraniteCave_Text_Magma3Defeated:
	.string "Hmph.$"

GraniteCave_Text_Magma3Post:
	.string "A kid like you couldn't understand.\n"
	.string "We're trying to bring actual change.\p"
	.string "Can you say the same?$"


GraniteCave_EventScript_Magma4::
	trainerbattle_single TRAINER_GRANITE_GRUNT_4, GraniteCave_Text_Magma4Intro, GraniteCave_Text_Magma4Defeated
	msgbox GraniteCave_Text_Magma4Post, MSGBOX_AUTOCLOSE
	end


GraniteCave_Text_Magma4Intro:
	.string "Were we sent here just to steal the\n"
	.string "emeralds?\p"
	.string "Or… For something else?$"


GraniteCave_Text_Magma4Defeated:
	.string "Ack! Forget it!$"

GraniteCave_Text_Magma4Post:
	.string "I joined Team Magma to protect the\n"
	.string "environment, but…\p"
	.string "I don't really see how this helps.$"


GraniteCave_EventScript_Magma5::
	trainerbattle_single TRAINER_GRANITE_GRUNT_5, GraniteCave_Text_Magma5Intro, GraniteCave_Text_Magma5Defeated
	msgbox GraniteCave_Text_Magma5Post, MSGBOX_AUTOCLOSE
	end


GraniteCave_Text_Magma5Intro:
	.string "Are you a member of Team Aqua?$"


GraniteCave_Text_Magma5Defeated:
	.string "I guess not.$"

GraniteCave_Text_Magma5Post:
	.string "How do I know that you're not Team Aqua?\p"
	.string "Easy. You're too strong to be one of\n"
	.string "them. Hah!$"


GraniteCave_EventScript_Magma6::
	trainerbattle_single TRAINER_GRANITE_GRUNT_6, GraniteCave_Text_Magma6Intro, GraniteCave_Text_Magma6Defeated
	msgbox GraniteCave_Text_Magma6Post, MSGBOX_AUTOCLOSE
	end


GraniteCave_Text_Magma6Intro:
	.string "Hey, who let you in?$"


GraniteCave_Text_Magma6Defeated:
	.string "I guess that answers that.$"

GraniteCave_Text_Magma6Post:
	.string "Look at us.\n"
	.string "We're being wiped out by a kid.\p"
	.string "Oh, Maxie…\n"
	.string "Forgive us.$"

GraniteCave_EventScript_Magma7::
	trainerbattle_single TRAINER_GRANITE_GRUNT_7, GraniteCave_Text_Magma7Intro, GraniteCave_Text_Magma7Defeated
	msgbox GraniteCave_Text_Magma7Post, MSGBOX_AUTOCLOSE
	end


GraniteCave_Text_Magma7Intro:
	.string "For the future of humanity!$"


GraniteCave_Text_Magma7Defeated:
	.string "Do you want to doom us all?$"

GraniteCave_Text_Magma7Post:
	.string "You've seen it, haven't you?\n"
	.string "Hoenn is going to the gutter.\p"
	.string "Only we can save the region.$"

GraniteCave_EventScript_Magma8::
	trainerbattle_single TRAINER_GRANITE_GRUNT_8, GraniteCave_Text_Magma8Intro, GraniteCave_Text_Magma8Defeated
	msgbox GraniteCave_Text_Magma8Post, MSGBOX_AUTOCLOSE
	end


GraniteCave_Text_Magma8Intro:
	.string "So many rocks… I love this place!$"


GraniteCave_Text_Magma8Defeated:
	.string "…Can I stay here a bit more?$"

GraniteCave_Text_Magma8Post:
	.string "I've heard that Devon's president\n"
	.string "likes rocks, too.\p"
	.string "Maybe he isn't such a bad guy.$"

GraniteCave_EventScript_Magma8::
	trainerbattle_single TRAINER_GRANITE_GRUNT_8, GraniteCave_Text_Magma8Intro, GraniteCave_Text_Magma8Defeated
	msgbox GraniteCave_Text_Magma8Post, MSGBOX_AUTOCLOSE
	end


GraniteCave_Text_Magma8Intro:
	.string "So many rocks… I love this place!$"


GraniteCave_Text_Magma8Defeated:
	.string "…Can I stay here a bit more?$"

GraniteCave_Text_Magma8Post:
	.string "I've heard that Devon's president\n"
	.string "likes rocks, too.\p"
	.string "Maybe he isn't such a bad guy.$"

GraniteCave_EventScript_Magma9::
	trainerbattle_single TRAINER_GRANITE_GRUNT_9, GraniteCave_Text_Magma9Intro, GraniteCave_Text_Magma9Defeated
	msgbox GraniteCave_Text_Magma9Post, MSGBOX_AUTOCLOSE
	end


GraniteCave_Text_Magma9Intro:
	.string "Our Admin is just up ahead.\p"
	.string "I don't know what he's doing, but\n"
	.string "I won't let you interrupt him!$"


GraniteCave_Text_Magma8Defeated:
	.string "Kyahaha!$"

GraniteCave_Text_Magma8Post:
	.string "Sure, go ahead.\n"
	.string "Our Admin, Tabitha, is super strong.\p"
	.string "You won't stand a single chance.$"