LittlerootTown_NeighborsHousr_MapScripts::
	.byte 0

LittlerootTown_NeighborsHousr_EventScript_Woman::
	msgbox LittlerootTown_NeighborsHousr_Text_Woman, MSGBOX_NPC
	end

LittlerootTown_NeighborsHousr_Text_Woman:
	.string "Have you heard of HEART SCALES?\n"
	.string "They're all the rage, I tell you!\p"
	.string "Scales of a POKéMON that was previously\n"
	.string "thought to be extinct are showing up all\l"
	.string "throughout HOENN, and no one knows why!\p"
	.string "Apparently, trainers are being asked to turn\n"
	.string "them in for a reward.\p"
	.string "Me, I couldn't care less. They're too pretty\n"
	.string "to get rid of!\p"
	.string "But hey, if you find one, do whatever you\n"
	.string "want with it.$"
