gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the HOENN region!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Let me introduce you my brave\p"
	.string "assistant.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Braver than me, at least!\n"
	.string "Ahah!\p"
	.string "Anyway…\p"
	.string "The region of HOENN is home to\n"
	.string "many strange weather phenomena.\p"
	.string "Surely you've noticed some of them.\p"
	.string "The formidable storm surrounding the\n"
	.string "island…\p"
	.string "The extreme volcanic activity…\p"
	.string "Not to mention, the permanent rainfalls,\n"
	.string "snowstorms, droughts and sandstorms\l"
	.string "that are raging throughout the region…\p"
	.string "There is very little we know about them.\p"
	.string "And to unravel these mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "…Oh, I apologize!\n"
	.string "I don't mean to scare you.\p"
	.string "I assure you, HOENN is quite a beautiful\n"
	.string "place to live in.\p"
	.string "There's all sorts of places to visit, from\n"
	.string "ancient ruins to modern cities.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Speaking of which…$"

gText_Birch_BoyOrGirl::
	.string "Tell me about yourself.$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
