gText_Birch_Welcome::
	.string "Hi! Thank you for taking the time to\n"
	.string "watch this message!\p"
	.string "Welcome to the Hoenn region!\p"
	.string "My name is Birch.\p"
	.string "But everyone calls me the Pokémon\n"
	.string "Professor.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Let me introduce you my brave\p"
	.string "assistant.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Braver than me, at least!\n"
	.string "Ahah!\p"
	.string "Anyway…\p"
	.string "Your father told me that he managed to\n"
	.string "convince you all to move to Hoenn.\p"
	.string "This beautiful region has sights the likes\n"
	.string "of which you will never see anywhere else.\p"
	.string "Surely you've noticed some of them.\p"
	.string "Formidable volcanoes… Mighty storms…\p"
	.string "Marshes, deserts, frozen valleys…\p"
	.string "Yes, throughout its history our region has\n"
	.string "been shaped by powerful and mysterious weather\l"
	.string "phenomena, which we are not able to fully explain.\p"
	.string "What makes Hoenn so unique?\n"
	.string "And how does that impact the ecosystem?\p"
	.string "To unravel these mysteries, I've\n"
	.string "been undertaking research.\l"
	.string "That's what I do.\p"
	.string "…Oh, I apologize!\n"
	.string "I don't mean to scare you.\p"
	.string "I assure you, Hoenn is quite a safe place\n"
	.string "to live in.\p"
	.string "There's all sorts of places to visit, from\n"
	.string "ancient ruins to bustling cities.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "But enough about me…$"

gText_Birch_BoyOrGirl::
	.string "Tell me about yourself.$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of Littleroot.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of Pokémon… where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my Laboratory.\p"
	.string "$"
