PetalburgCity_House3_MapScripts::
	.byte 0


PetalburgCity_House3_Eventscript_Camper::
	msgbox PetalburgCity_House3_Text_Camper, MSGBOX_NPC
	release
	
	

PetalburgCity_House3_Text_Camper:
	.string "Having your own Gym sounds\n"
	.string "awesome.\p"
	.string "Me, I'd fill it with spinning floors.\n"
	.string "And hidden switches to find!\p"
	.string "Oh, oh, and quizzes!\n"
	.string "And pitfalls!\p"
	.string "…Maybe it's best if I don't get my own\n"
	.string "Gym.$"