OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "Wild Pokémon, when they get defeated,\n"
	.string "can drop some useful material.\p"
	.string "Things like fur, claws, even minerals…\p"
	.string "Don't worry! They shed them naturally.\p"
	.string "Anyway, these are worth a small amount of\n"
	.string "money.\p"
	.string "So if you're just short on cash, fighting\n"
	.string "wild Pokémon can be a good idea.$"
