OldaleRuinsEntrance_1_MapScripts::
	.byte 0

EventScript_OldaleRuinsInterior_Boy::
	msgbox Text_OldaleRuinsInterior_ThisBlows, MSGBOX_NPC
	return

Text_OldaleRuinsInterior_ThisBlows:
	.string "I'm visiting from FORTREE, but man…\n"
	.string "This kinda blows.\p"
	.string "They look just like our houses, except\n"
	.string "not even built on trees!\p"
	.string "Come on, ancient people!\n"
	.string "You can do better than this!$"